[Cleanup] add disposable to VfsRootAccess.allowRootAccess() invocations
Currently we get
```
WARN: This method in 'com.intellij.openapi.vfs.newvfs.impl.VfsRootAccess' is deprecated and going to be removed soon. Use `allowRootAccess(Disposable, String...)` instead
com.intellij.util.DeprecatedMethodException: This method in 'com.intellij.openapi.vfs.newvfs.impl.VfsRootAccess' is deprecated and going to be removed soon. Use `allowRootAccess(Disposable, String...)` instead
	at com.intellij.util.DeprecatedMethodException.report(DeprecatedMethodException.java:28)
```
in our logs which indicates that the invocation without a Disposable is deprecated.
PiperOrigin-RevId: 366307204